### ISSUE TITLE
Adapter legt keine Objekte an

### ISSUE THREAD

**Issue by Rippchen4711** [schmupu/ioBroker.ring#12]
Hallo 
Ich habe den Adapter installiert.
Leider legt dieser keine Objekte an.
In der Log steht folgendes:

ring.1 | 2019-12-01 20:43:28.791 | info | (29388) Ring adapter uses API: ring-api
-- | -- | -- | --
ring.1 | 2019-12-01 20:43:28.790 | info | (29388) Starting Adapter ring.1 in version 1.0.5
ring.1 | 2019-12-01 20:43:28.741 | info | (29388) starting. Version 1.0.5 in /opt/iobroker/node_modules/iobroker.ring, node: v8.16.0

**Comment by schmupu** [comment]
Es wäre hilfreich wenn du ein paar mehr Infos angeben würdest. Welches Gerät möchtest du z.B. einbinden? Welche API hast du in der ioBroker Ring Konfiguration angegeben? Wo läuft ioBroker? Hat ioBroker eine Verbindung zum Internet und funktioniert die DNS Auflösung in ioBroker?

**Comment by schmupu** [comment]
Was mir noch einfällt. Der Ring Adapter funktioniert nicht mit "two factor authentication". Das musst du disablen.

**Comment by Rippchen4711** [comment]
Ring Video Dorrbell 2
ring-Api
Läuft auf einem Tinkerboard mit Internet.
DNS OK

**Comment by schmupu** [comment]
Hast du die andere API versucht? Wenn das nicht hilft, den Debug Modus aktivieren. Was für Meldungen siehst du dort?

**Comment by Rippchen4711** [comment]
ring.1 | 2019-12-02 20:18:22.760 | debug | (25431)  Devices:  {"doorbells":[],"authorisedDoorbells":[{"id":32608406,"description":"Haustür","device_id":"4c24986fa9e3","time_zone":"Europe/Berlin","subscribed":true,"subscribed_motions":true,"batte
-- | -- | -- | --
ring.1 | 2019-12-02 20:18:22.343 | debug | (25431) Ring: {"events":{"domain":null,"_events":{},"_eventsCount":0,"_maxListeners":100}}
ring.1 | 2019-12-02 20:18:07.341 | debug | (25431)  Devices:  {"doorbells":[],"authorisedDoorbells":[{"id":32608406,"description":"Haustür","device_id":"4c24986fa9e3","time_zone":"Europe/Berlin","subscribed":true,"subscribed_motions":true,"batte
ring.1 | 2019-12-02 20:18:06.967 | debug | (25431) Ring: {"events":{"domain":null,"_events":{},"_eventsCount":0,"_maxListeners":100}}
ring.1 | 2019-12-02 20:17:51.966 | debug | (25431)  Devices:  {"doorbells":[],"authorisedDoorbells":[{"id":32608406,"description":"Haustür","device_id":"4c24986fa9e3","time_zone":"Europe/Berlin","subscribed":true,"subscribed_motions":true,"batte
ring.1 | 2019-12-02 20:17:51.363 | debug | (25431) Ring: {"events":{"domain":null,"_events":{},"_eventsCount":0,"_maxListeners":100}}
ring.1 | 2019-12-02 20:17:36.360 | debug | (25431)  Devices:  {"doorbells":[],"authorisedDoorbells":[{"id":32608406,"description":"Haustür","device_id":"4c24986fa9e3","time_zone":"Europe/Berlin","subscribed":true,"subscribed_motions":true,"batte
ring.1 | 2019-12-02 20:17:35.995 | debug | (25431) Ring: {"events":{"domain":null,"_events":{},"_eventsCount":0,"_maxListeners":100}}
ring.1 | 2019-12-02 20:17:20.994 | debug | (25431)  Devices:  {"doorbells":[],"authorisedDoorbells":[{"id":32608406,"description":"Haustür","device_id":"4c24986fa9e3","time_zone":"Europe/Berlin","subscribed":true,"subscribed_motions":true,"batte
ring.1 | 2019-12-02 20:17:20.646 | debug | (25431) Ring: {"events":{"domain":null,"_events":{},"_eventsCount":0,"_maxListeners":100}}
ring.1 | 2019-12-02 20:17:20.644 | debug | (25431) Ring: {"events":{"domain":null,"_events":{},"_eventsCount":0,"_maxListeners":100}}
ring.1 | 2019-12-02 20:17:17.691 | info | (25431) Ring adapter uses API: ring-api
ring.1 | 2019-12-02 20:17:17.691 | info | (25431) Starting Adapter ring.1 in version 1.0.5
ring.1 | 2019-12-02 20:17:17.651 | info | (25431) starting. Version 1.0.5 in /opt/iobroker/node_modules/iobroker.ring, node: v8.16.0
ring.1 | 2019-12-02 20:17:12.342 | info | (24070) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
ring.1 | 2019-12-02 20:17:12.341 | info | (24070) terminating
ring.1 | 2019-12-02 20:17:12.340 | info | (24070) Closing Adapter
ring.1 | 2019-12-02 20:17:12.338 | info | (24070) Got terminate signal TERMINATE_YOURSELF

**Comment by Rippchen4711** [comment]
Keine Idee mehr?

**Comment by schmupu** [comment]
leider nein, außer die andere API testen. Leider gibt Ring keine Informationen preis.

**Comment by oggy79** [comment]
Hallo!

Habe die Version 1.0.6 im Einsatz auf dem ioBroker.
Von 3 Kameras (Doorbell, 2x Spotlight wired) wird nur die Doorbell angelegt.
Adapter deinstalliert, komplett alles neu versucht, 2 Faktor-Authentifizierung ist aus ... kann das was damit zu tun haben, dass sich nun alle Geräte verknüpfen lassen (Video, Beleuchtung, ...).

In der akt Version kann ich die API auch nicht umstellen.
Das Logfile zeigt auch keine Fehler oder sonst. Infos an, ausser zu der erkannten Doorbell.
Im Ring-account kann ich natürlich auf alle 3 Kameras zugreifen, wie auch in der App am Handy.

Vielen Dank für Dein Feedback und schon mal schöne Feiertage.

**Comment by schmupu** [comment]
Es wird aktuell nur die Doorbell unterstützt, da ich die anderen Geräte nicht besitze. Diese sind aber zwingend notwendig für die Entwicklung.

**Comment by oggy79** [comment]
Danke, für Dein schnelles Feedback.
Leider hat es mit einer älteren Version von Dir funktioniert.

**Comment by schmupu** [comment]
Die älteren APIs werden leider nicht mehr unterstützt . Damit gibt es seit ein paar Tagen Probleme mit Authentifizierung.  Die "alten" APIs werden auch nicht mehr von den Leuten die diese bereitstellen weiterentwickelt.

**Comment by schmupu** [comment]
@oggy79 , kannst Du einmal in der ioBroker Admin Oberfläche unter Instanzen den Debug Modus für das Logging einstellen. Dann schauste Du bitte einmal ob Du die Spotlight wired im Logfile auftauchen. Die Info benötige ich! Bitte aber nur diese Einträg und nicht alles! Kannst Du mir auch als Email schicken  an iobroker @ stueben.de

**Comment by oggy79** [comment]
bei mir wird aktuell nur die Doorbell im Debuglog angezeigt

**Comment by schmupu** [comment]
Dann werden die Spotlights leider nicht von der API unterstützt. Dann kann ich die leider nicht im Adapter einbauen

**Comment by oggy79** [comment]
ok, danke
