### ISSUE TITLE
Authenitication/Authorisation Error 401

### ISSUE THREAD

**Issue by Hini2001** [schmupu/ioBroker.ring#13]
Seit heute Nacht ca. 1:30 Uhr spuckt der Ring-Adapter alle naselang folgenden und ähnliche Fehler aus:
![image](https://user-images.githubusercontent.com/58652465/71196259-fbe55580-228f-11ea-88b9-9e4dfd968f8b.png)

Hat sich die Authorisierung bei Ring geändert? Liegt es an mir? :-/

2Wege-Authorisierung ist AUS.
App funktioniert.
Webseite ebenso.
Nutzer und Passwort sind korrekt.

Wechsel auf "Doorbot" bringt:
Could not get all doorbell devices in getAllRingsDevices(). Could not get device instance in method getDevices(). Error: JSON parse error from ring, check logging..

Zwischenzeitlich war die Fehlemeldung auch:
Could not get ring instance in method getRing(). Error: session failed to initialise, cannot create ring-api instance --caused-by-> could not get a session token given auth token

Ich glaube vermuten zu können, dass irgendwas mit der Anmeldung nicht hinhaut. :-)

Hat noch wer dieses Problem? Hat bitte irgendwer ne Lösung für mich? :-(

Vielen Dank. Auch für die geleistete Arbeit und alles. TOP!

Grüße
Hinrich

**Comment by schmupu** [comment]
das scheint Ring etwas geändert zu haben. Leider gibt es von ring.com keiner offizielle API. Ich werde nächste Woche schauen, ob ich irgendetwas tun kann. 
Ich persönlich würde die Klingel nicht wieder kaufen.

**Comment by Hini2001** [comment]
Hey. Vielen Dank für die schnelle Antwort. Wäre echt cool.
Findest du die Klingel so schlecht? Oder nur weil es keine API gibt? 
Was ist denn mit dieser Internetseite: https://ring.com/partners

Sorry, aber ich habe echt nicht so die Ahnung. Aber dort steht doch etwas zur API?
Vielleicht hilft dir das ggf?!

**Comment by lordnaicon** [comment]
Hi bei mir schaut es genau so aus. Hoffe es gibt eine lösung. Danke in voraus
mfg

`

ring.0 | 2019-12-20 14:58:35.829 | info | (25052)  Could not get all doorbell devices in getAllRingsDevices(). Could not  get device instance in method getDevices(). Error: JSON parse error from  ring, check logging..
-- | -- | -- | --
ring.0 | 2019-12-20 14:57:21.862 | info | (25052) Could not get all doorbell devices in getAllRingsDevices().  Could not get device instance in method getDevices(). Error: JSON parse  error from ring, check logging..
ring.0 | 2019-12-20 14:56:18.102 | info | (25052) Could not get all doorbell devices in getAllRingsDevices().  Could not get device instance in method getDevices(). Error: JSON parse  error from ring, check logging..
ring.0 | 2019-12-20 14:54:54.705 | info | (25052) Could not get all doorbell devices in getAllRingsDevices().  Could not get device instance in method getDevices(). Error: JSON parse  error from ring, check logging..
ring.0 | 2019-12-20 14:53:50.278 | info | (25052) Could not get all doorbell devices in getAllRingsDevices().  Could not get device instance in method getDevices(). Error: JSON parse  error from ring, check logging..
ring.0 | 2019-12-20 14:52:42.195 | info | (25052) Could not get all doorbell devices in getAllRingsDevices().  Could not get device instance in method getDevices(). Error: JSON parse  error from ring, check logging..
ring.0 | 2019-12-20 14:52:20.209 | info | (25052) Could not get all doorbell devices in getAllRingsDevices().  Could not get device instance in method getDevices(). Error: JSON parse  error from ring, check logging..
ring.0 | 2019-12-20 14:51:48.563 | info | (25052) Ring adapter uses API: doorbot
ring.0 | 2019-12-20 14:51:48.561 | info | (25052) Starting Adapter ring.0 in version 1.0.5
ring.0 | 2019-12-20 14:51:47.985 | info | (25052) starting. Version 1.0.5 in /opt/iobroker/node_modules/iobroker.ring, node: v10.18.0
ring.0 | 2019-12-20 14:51:43.002 | info | (24658) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
ring.0 | 2019-12-20 14:51:43.001 | info | (24658) terminating
ring.0 | 2019-12-20 14:51:42.999 | info | (24658) Closing Adapter
ring.0 | 2019-12-20 14:51:42.996 | info | (24658) Got terminate signal TERMINATE_YOURSELF
ring.0 | 2019-12-20 14:51:24.350 | info | (24658) Could not get ring instance in method getRing(). Error: ring  gave a seemingly valid authentication/authorisation, but the failed  --caused-by-> problem GETing endpoint https://api.ring.com/cli
ring.0 | 2019-12-20 14:50:20.975 | info | (24658) Could not get ring instance in method getRing(). Error: ring  gave a seemingly valid authentication/authorisation, but the failed  --caused-by-> problem GETing endpoint https://api.ring.com/cli
ring.0 | 2019-12-20 14:49:13.173 | info | (24658) Could not get ring instance in method getRing(). Error: ring  gave a seemingly valid authentication/authorisation, but the failed  --caused-by-> problem GETing endpoint https://api.ring.com/cli
ring.0 | 2019-12-20 14:48:10.064 | info | (24658) Could not get ring instance in method getRing(). Error: ring  gave a seemingly valid authentication/authorisation, but the failed  --caused-by-> problem GETing endpoint https://api.ring.com/cli
ring.0 | 2019-12-20 14:47:07.374 | info | (24658) Could not get ring instance in method getRing(). Error: session  failed to initialise, cannot create ring-api instance --caused-by->  could not get a session token given auth token eyJhbGciOiJI
ring.0 | 2019-12-20 14:45:51.936 | info | (24658) Could not get ring instance in method getRing(). Error: ring  gave a seemingly valid authentication/authorisation, but the failed  --caused-by-> problem GETing endpoint https://api.ring.com/cli
ring.0 | 2019-12-20 14:45:28.935 | info | (24658) Could not get ring instance in method getRing(). Error: ring  gave a seemingly valid authentication/authorisation, but the failed  --caused-by-> problem GETing endpoint https://api.ring.com/cli
ring.0 | 2019-12-20 14:45:25.674 | info | (24658) Ring adapter uses API: ring-api
ring.0 | 2019-12-20 14:45:25.673 | info | (24658) Starting Adapter ring.0 in version 1.0.5
ring.0 | 2019-12-20 14:45:25.590 | info | (24658) starting. Version 1.0.5 in /opt/iobroker/node_modules/iobroker.ring, node: v10.18.0

`

**Comment by schmupu** [comment]
Also ich habe eine erste Lösung umgesetzt. Dafür meldet Ihr Euch in ioBroker auf der Admin Oberfläche an. Dort geht Ihr auf den Reiter Adapter. Oben findet Ihr die kleine GitHub Katze (Installieren aus eigener URL) und klickt auf diese. Nun wählt Ihr in der Dropdownliste den ring Adapter aus und installiert diesen. 
Über eine Rückmeldung würde ich mich freuen.

**Comment by lordnaicon** [comment]
Hi, funktioniert wider alles ohne Fehler Meldungen. Danke super Arbeit.
mfg

**Comment by Hini2001** [comment]
Hey super vielen dank. Alles läuft wieder perfekt. Vielen Dank und frohe Weihnachten.

**Comment by mcdhrts** [comment]
Hi @schmupu,
kannst du bitte nach den positiven Rückmeldungen die neue Version 1.0.6 ins offizielle ioBroker/ioBroker.repositories schieben damit alle die Aktualisierung bekommen ohne händisch nachschauen zu müssen (und aktualisieren)?
Danke dir
