### ISSUE TITLE
It ignores that my web adapter uses https

### ISSUE THREAD

**Issue by ldittmar81** [schmupu/ioBroker.ring#18]
I notice that my snapshot link is wrong, because I use https and the adapter gives me a http url for the snapshot.

---

**System data:**

Model: Intel(R) Celeron(R) CPU J3455 @ 1.50GHz
RAM: 7.64 GB
Node.js: v10.18.1
NPM: 6.13.4
Platform: linux
Distribution: Debian GNU/Linux
Architecture: x64
JS-Controller (1): 2.2.8
Admin: 4.0.2
Ring: 1.0.6

> *created by ioBroker.info*

**Comment by schmupu** [comment]
fixed. In version 1.0.7 http or https will be recognized
