### ISSUE TITLE
Leider keinerlei Funktion mehr

### ISSUE THREAD

**Issue by elzershark** [schmupu/ioBroker.ring#19]
Wer den Ring Adapter gerne wieder benutzen möchte:
Es muss min. die Version 1.0.7 sein.
Den installieren und in der Einstellung !!!alles löschen!!!
!!!Nichts anhaken!!!
Putty öffnen und
npx -p ring-client-api ring-auth-cli
eingeben.
Zugangsdaten vom Ring Account eingeben.
E-Mail öffnen und den Code in Putty eintragen.
Den jetzt angezeigten Tocken kopieren.
Diesen im Adapter Eintragen und auf Speichern und schließen klicken.
Und wie gesagt...
Im Adapter
!!!Alles löschen!!! Alles muss Blank sein.
!!!Nichts anhaken!!!
Nur unten den Tocken Eintragen und speichern

**Comment by mcdhrts** [comment]
@elzershark bei mir war das gleiche nachdem ring umgestellt hat das man auch wenn die Zwei Faktor Authentifizierung ausgeschaltet ist einen extra Code angegeben muss der einem per E-Mail zugesendet wird (also meiner Meinung nach dann auch wieder ein zwei Faktor Authentifizierung). 
Momentan wird das vom Adapter nicht abgefangen. Es kann aber gelöst werden in dem du dir einen Token holst und dann beim Login vom Adapter nur den Token ausfüllst. 

Anleitung für den Token:
https://github.com/dgreif/ring/wiki/Two-Factor-Auth

Grüße
McD_HRTS

**Comment by Drongo76** [comment]
Hallo, ich bekomme das nicht hin mit Token. 
Bekommen immer diese Fehler. Email und Passwort sind richtig eingegeben 

Error: Failed to fetch oauth token from Ring. Verify that your email and password are correct. (error: )
    at RingRestClient.<anonymous> (/data/data/com.termux/files/home/.npm/_npx/15939/lib/node_modules/ring-client-api/lib/api/rest-client.js:132:23)
    at Generator.throw (<anonymous>)
    at rejected (/data/data/com.termux/files/home/.npm/_npx/15939/lib/node_modules/ring-client-api/lib/api/rest-client.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)  `

**Comment by elzershark** [comment]
Wer den Ring Adapter gerne wieder benutzen möchte:
Es muss min. die Version 1.0.7 sein.
Den installieren und in der Einstellung alles löschen.
Nichts anhaken.
Putty öffnen und
npx -p ring-client-api ring-auth-cli
eingeben.
Zugangsdaten vom Ring Account eingeben.
E-Mail öffnen und den Code in Putty eintragen.
Den jetzt angezeigten Tocken kopieren.
Diesen im Adapter Eintragen und auf Speichern und schließen klicken.

**Comment by stoepfel** [comment]
Hallo,

Nach dem Update auf 1.0.7 (mit 2FA, als auch ohne) und einem reboot des Raspberry Pi 4 kann ich nicht mehr auf die Admin-Weboberfläche (Port 8081) zugreifen. Der Ladekreis dreht sich endlos. Habe ioBroker komplett neu aufgesetzt und nur mit Ring-Adapter getestet. Der Reboot und Zugriff auf die Weboberfläche bei Version 1.0.5 klappt problemlos. Woran liegt das? Benötige dringend 1.0.7 für die 2FA. SSH-Zugriff funktioniert in beiden Fällen und die Instanzen laufen auch.
![FD22A1AC-D4F0-4479-9C9E-9B13CADE6AC3](https://user-images.githubusercontent.com/63659971/79246696-d4874980-7e79-11ea-8c38-fcac05b570b3.png)

**Comment by stoepfel** [comment]
Habe dazu folgenden Beitrag gefunden: [https://github.com/ioBroker/ioBroker.admin/issues/485](url). Nachdem ich ioBroker.admin irgendwie auf Version 4.0.5 aktualisiert bekommen habe, geht es wieder.
