### ISSUE TITLE
Ring will eine Login Authentifizierung

### ISSUE THREAD

**Issue by digitalnaiveDE** [schmupu/ioBroker.ring#21]
Ich bekomme in meinem E-Mailpostfach eine große Mengen von Anfragen, den Login den ich via Adapter produziere zu authentifizieren. Wie gehe ich denn mit diesem Problem am besten um?

**Comment by elzershark** [comment]
https://github.com/schmupu/ioBroker.ring/issues/19

**Comment by schmupu** [comment]
Leider nur so möglich. Terminal öffnen und folgenden Befehl eingeben:
```
node /opt/iobroker/node_modules/iobroker.ring/node_modules/ring-client-api/ring-auth-cli.js 
```
Anschließend den Token in ioBroker beim Ring Adapter eintragen
