### ISSUE TITLE
Akku? StickUpCam?

### ISSUE THREAD

**Issue by Hini2001** [schmupu/ioBroker.ring#22]
Hallo,

ersteinmal super, dass der Adapter (1.0.7) wieder funktioniert. Klappt echt super.
Nur fehlen mir die Info-Datenpunkte wie Batterie etc.? Im DEBUG-Log werden diese Daten unter Health dargestellt. Aber leider gibt es keinen Datenpunkt dafür.

`Health: {"id":xxxxxxxxxx,"wifi_name":"xxxxxxxxxxx","battery_percentage":"97","battery_percentage_category":"very_good","battery_voltage":null,"battery_voltage_category":null,"latest_signal_strength
`

Seit neuestem wohnt auch eine StickUpCam hier. Ich hatte gehofft diese wird ebenfalls unterstützt. Aber leider gibt es gar keine Datenpunkte. :-( Und auch im Logfile wird nichts angezeigt. Habe den Adapter bereits neugestartet. Muss ich ihn komplett neu installieren (inkl. Token Erstellung, etc.)? Oder werden die Cams gar nicht unterstützt? (was sehr schade wäre).

**Comment by Hini2001** [comment]
Also eine komplette Neuanlegung der Instanz hat auch leider keine StickUpCam datenpunkte angelegt. Ebensowenig die Akku Informationen aus dem DebugLog.
Was kann ich noch tun bzw. gibt es eine Möglichkeit die Datenpunkte zu erhalten? Und die Cam einzubinden?

**Comment by schmupu** [comment]
Der Adapter unterstützt nur die Ring Video Doorbell. Leider habe ich momentan keine Zeit den Adapter für andere Geräte zu erweitern.

**Comment by schmupu** [comment]
Ich habe noch einen Debug Punkt eingefügt um alle Kameras im Logfile anzuzeigen. Kannst Du bitte einem die Version 1.1.2 downloaden und den Adapter im debug Modus starten. Suche im Logfile nach "'Ring Cameras:". Kannst Du dort etwas finden mit  Stick Up Cam?

**Comment by sunshower2** [comment]
sorry, habe leider keine Stick Up Cam, bitte mal bei Hini2001 nachfragen

**Comment by schmupu** [comment]
@Hini2001 , kannst Du bitte den Adapter in Version 1.1.2 über GitHub laden und dann  den Adapter im debug Modus starten. Suche im Logfile nach "'Ring Cameras:". Kannst Du dort etwas finden mit Stick Up Cam?

Laden der Version 1.1.2:
Anmelden auf der ioBroker Admin Oberfläche. Auf das den Reiter Adapter wechseln. Dort oben auf die GitHub Katze (laden über externe URL) klicken und in der Liste den Ring Adapter auswählen und laden. Ist das durch, den Ring Adapter neu starten.

**Comment by Hini2001** [comment]
Hey... super. Im DEBUG-Log taucht meine Camera auf. Steht zwar nicht stickupcam. Aber der Name meiner Kamera (Einfahrt) wird angezeigt. Aber Datenpunkte habe ich keine. Allerdings werden auch wieder die Akku-Infos angezeigt!!!

**Comment by schmupu** [comment]
ich benötige genau die Debug Infos. Die privaten Daten bitte vorher löschen. Entweder du hängst das Debug Infos ans Ticket oder schickst mir diese als Email an iobroker@stueben.de

**Comment by Hini2001** [comment]
bekommst gleich ne mail. muss nur die ganzen privaten daten rauslöschen...

**Comment by schmupu** [comment]
okay, ich habe versucht die Kamera mit zu integrieren. Du kannst bitte nochmals die Version 1.1.2. von GitHub wie oben beschrieben laden und die Ring Instanz neu starten. 
Ich bin gespannt. Ich hoffe es werden alle Geräte angelegt.

**Comment by Hini2001** [comment]
ja geil. Datenpunkte sind da. Kamera wird angezeigt. Top.
Werde morgen mal intensiv testen und dir hier berichten, ok?

Vielen Dank. Top.

**Comment by schmupu** [comment]
Super, ich bin gespannt auf deinen Testbericht.

**Comment by Hini2001** [comment]
@schmupu hier der erste Erefahrungsbericht:

Guten Morgen.
Erst einmal noch mal vielen lieben Dank für die Hilfe. Die Cam wurde super eingebunden und es funktioniert alles relativ reibungslos.
Wie auch schon bei der Doorbell gibt es häufiger Probleme mit den SNAPSHOTS:
`Error: Error setSanpshot): Error: Could not get Snapshot for xxxxxxxx in getSnapshot(). Error: Snapshot failed to refresh after 60 attempts`
Dies betrifft die Cam nach ersten Tests häufiger als die Doorbell. Der state kind wird zwar jedesmal auf on_demand geändert (auch neues verhalten, vorher nur motion und ding). Aber der Snapshot wird nicht erstellt mit der o.a. Meldung im Log.

Was definitiv sehr gut klappt ist die Livestream Erstellung. Diese klappt nahezu immer (aktuell alle 15 Minuten ein 10 Sekunden video).

Soweit der erste Test. Adapter läuft seit über 24 Stunden stabil.

Eine Kleinigkeit ist mir noch aufgefallen im Log. Ein kleiner Rechtschreibfehler beim starten des Livestreams:
`Sarting LiveStream for 10 sec.`
da fehlt halt ein "T". Aber dies ist natürlich Schmuck am Nachthemd, sollte aber dennoch Erwähnung finden.

Also vielen Dank noch mal.
Benötigst du weitere Informationen?

**Comment by schmupu** [comment]
Den Fehler `Snapshot failed to refresh after 60 attempts` werde ich leider nicht fixen können. Der kommt aus einer Library die ich nutze.
Rechtschreibfehler habe ich korrigiert. Die Version 1.1.2 werde ich heute Abend veröffentlichen.
Bitte umbedingt nachher nochmals laden, da ich ein paar Änderungen vorgenommen habe.

**Comment by Hini2001** [comment]
Alles klar.
Vielen Dank.

Was halt sehr auffällt, die doorbell macht eigentlich 75% der geforderten
Aufnahmen. Spätestens nach nem Neustart geht es auch fast immer.
Aber die Cam hat glaube 2 Aufnahmen gemacht und seitdem geht's halt gar
nicht mehr.
Vielleicht sind die Abstände auch zu kurz?
Der livestream funktioniert fast zu 98% immer. Mega selten das der mal
nicht klappt.
Und wie gesagt beide Geräte zeigen beim Kind Status on_demand auch an. Also
scheint das zumindest zu klappen. Keine Ahnung woran es dann liegt.

Ich hoffe, der Test war für dich hilfreich und umfangreich genug.
Wenn du noch was brauchst sag bitte bescheid.

Vielen Dank noch mal. Top Arbeit.

Thorsten Stueben <notifications@github.com> schrieb am Di., 5. Mai 2020,
20:42:

**Comment by schmupu** [comment]
Der Test hat super geholfen. Danke dafür! Der Fehler `Snapshot failed to refresh after 60 attempts `  ist hier gut beschrieben:  https://github.com/dgreif/ring/issues/293
