### ISSUE TITLE
Kein Datenpunkt für Akkustand  bei doorbell

### ISSUE THREAD

**Issue by sunshower2** [schmupu/ioBroker.ring#25]
Hallo,
leider scheint wie in #22 der Datenpunkt für die Batterieanzeige nicht nur bei der Stick UP Cam zu fehlen, sondern auch bei der doorbell_v3 bzw. doorbell_v4.
Es wird nur der Datenpunkt external_connection angelegt, aber leider keiner für den Batteriestand.
Im laut Log wird er aber in der Abfrage mit übergeben: "battery_life":"13".

Wäre es möglich, diesen Datenpunkt hinzuzufügen?

**Comment by schmupu** [comment]
Mist, da war ein kleiner Tippfehler im Programm. Es wird jetzt der Batteriestatus in der Version 1.1.2 angezeigt. Wobei ich das Feld battery_life nich finden. 
So sieht es jetzt aus:
<img width="1083" alt="issue25" src="https://user-images.githubusercontent.com/38919572/80921444-b759e280-8d76-11ea-8819-c8f1cf6f6d8f.png">
Kannst Du die Version 1.1.2 bitte testen und mir eine kurze Rückmeldung geben:

_Anmelden auf der ioBroker Admin Oberfläche. Auf das den Reiter Adapter wechseln. Dort oben auf die GitHub Katze (laden über externe URL) klicken und in der Liste den Ring Adapter auswählen und laden. Ist das durch, den Ring Adapter neu starten._

**Comment by sunshower2** [comment]
Hi, das ging aber schnell. Ja, funktioniert jetzt, vielen Dank.
Der Batteriestatus scheint 2 mal vorhanden zu sein, einmal im Health als battery-percentage und einmal in der allgemeinen Beschreibung als battery_life, von daher passt es für mich :-)
#
[34mdebug[39m: ring.0 (19928) Doorbell: {"id“:xxxxxxxxx,"description“:"xxxxx","device_id“:"xxxxxx","time_zone":"Europe/Berlin","subscribed":true,"subscribed_motions":true,"battery_life":"91","external_connection":false,"firmware_version":"Up to Date","kind":"doorbell_v4","latitude“:xxxxxx,"longitude":1xxxx,"address“:“xxxx,“…..

Etwas verwirren ist noch, dass bei external-connection nichts (also auch kein false) eingetragen ist, ist aber nur ein reines Schönheitsproblem.

**Comment by schmupu** [comment]
Mit dem external Link habe ich gefunden. Bitte Version 1.1.2 wie oben beschrieben und neu starten. Dann habe ich für Issue #22  auch noch etwas eingebaut

**Comment by schmupu** [comment]
Den external-connection Fehler habe ich gefunden. Bitte Version 1.1.2 wie oben beschrieben nochmals laden  und neu starten. Dann habe ich für Issue #22  auch noch etwas eingebaut

**Comment by sunshower2** [comment]
Ja, jetzt sind alle Datenpunkte richtig belegt, vielen Dank.
