### ISSUE TITLE
Snapshot beim Klingeln

### ISSUE THREAD

**Issue by ldittmar81** [schmupu/ioBroker.ring#26]
Ein Datenpunkt der beim Klingeln automatisch ein Snapshot macht/bereit stellt würde alles vereinfachen.

**Comment by schmupu** [comment]
Hmm, das wundert mich eigentlich. Eigentlich wird ein Snapshot und Livestream bei jeder Bewegung und wenn es klingelt erstellt. 
Kannst Du das bitte in der Version 1.1.2 nochmals testen. Schaue im Logfile ob da etwas mit Starting Livestream ... steht

**Comment by michiproep** [comment]
Hallo @schmupu, ich würde das Thema gerne nochmal öffnen.
Mein Adapter (v3.04) zieht nur beim Neustart einen Snapshot. Bewegungen erkennt er unter Events, aber der zugehörige Snapshot wird nicht gezogen.
![grafik](https://user-images.githubusercontent.com/12296115/193529538-6f786390-cc13-454a-ab75-31615b259d10.png)
