### ISSUE TITLE
Adapter legt keine Objekte an

### ISSUE THREAD

**Issue by mcdhrts** [schmupu/ioBroker.ring#28]
Hey Schmupu, 
habe mir gerade direkt die neuste Version 1.1.2 gezogen und habe folgendes Problem:
Der Adapter legt mir zu meiner Doorbell kein Objekte an. Früher 1.0.x als ich das letzte mal noch aktiv hatte hat das geklappt.
E-Mail, Passwort und Token sind drin, Verbindung zu ring steht.
Adapter ist grün.

So sieht der Objektexplorer aus:
![image](https://user-images.githubusercontent.com/37240726/81109832-050f5000-8f1b-11ea-945d-39e1707db620.png)

das gibt das Log im Debug Modus aus:
![image](https://user-images.githubusercontent.com/37240726/81110137-6df6c800-8f1b-11ea-9750-0ec4ffcd6aee.png)

Die Daten kann er wohl gut auslesen. Im JSON im Debug log stehen alle Werte drin, hab mir die im Log komplett angeschaut. Sieht gut aus.

Hast du eine Idee hierzu?

Danke und Grüße
McD_HRTS

**Comment by schmupu** [comment]
Versuche es einmal mit einem Refreshen oder Ring Adapter stoppen und neu starten. Steht denn etwas unter Info?

**Comment by mcdhrts** [comment]
Ring Adapter habe ich schon mehrfach gestoppt und neugestartet.

Habe auch einmal den Adapter komplett gelöscht (alle Objekte weg). Dann neu installiert und neu verbunden. Ergebnis war das er mir dann nicht mal mehr den ring.0 Ordner angelegt hat.

Um einen Fehler weiter auszuschließen habe ich es dann auch nochmal an einer frischen ioBroker Test Installation versucht (inkl. auf anderer Hardware) auf der dann nichts anderes installiert ist. 
Ergebnis ist dasselbe. Er hat mir auch hier nicht mal den ring.0 angelegt. Sehr eigenartig.

Die JSON im Debug Log vom Device zeigt mir alles vom meiner Ring an. Also das sieht eigentlich gut aus.

Funktioniert bei dir es mit einer Neuinstallation?

**Comment by schmupu** [comment]
Und funktioniert bei dir die Version 1.1.0 oder 1.1.1?

**Comment by schmupu** [comment]
Was ist wenn du den Adapter nicht im Debug sondern im Info Modus startest? Was siehst du dann im Logfile?

**Comment by mcdhrts** [comment]
Habe jetzt 1.1.0 getestet und 1.1.0 funktioniert, Objekte werden angelegt und sieht gut aus.
Kann auch noch 1.1.1 testen wenn du willst.

**Comment by mcdhrts** [comment]
Hab 1.1.1 auch kurz getestet, geht ja schnell.
Instanz entfernt, Adapter auf 1.1.1 gehoben, Instanz neu erstellt. Sieht gut aus!

Habe dann auch jetzt gleich nochmal 1.1.2 getestet um zu prüfen ob einfach gestern was nicht funktioniert hat. Und geht nicht. Mit 1.1.2 passt also bei mir auf jeden fall was nicht.
Was im LOG fehlt bei 1.1.2 das bei 1.1.0 und 1.1.1 kommt ist:
`Starting Ring Device for Id xxxx`

**Comment by schmupu** [comment]
Welche Node Version hast du installiert? Ich habe es eben nochmals versucht auf einem komplett leeren System mit der Version 1.1.2 und alle Objekte wurden angelegt.

**Comment by schmupu** [comment]
Ich habe eben eine Version 1.1.3 erstellt die Du aber nur über GitHub downloaden kannst. Kannst Du die Version bitte einmal testen. Ich habe in der Version den Befehl process.nextTick() durch setImidate() ersetzt. 

Laden der Version 1.1.3:
Anmelden auf der ioBroker Admin Oberfläche. Auf das den Reiter Adapter wechseln. Dort oben auf die GitHub Katze (laden über externe URL) klicken und in der Liste den Ring Adapter auswählen und laden. Ist das durch, den Ring Adapter neu starten.

**Comment by Sarzeau** [comment]
Hallo schmupu,
habe eben hier mitgelesen. Vielen Dank für den Adapter! 1.1.3 legt jetzt wieder Objekte an, aber die Werte bleiben bislang leer. Wie löse ich da einen Refresh aus?
Gruß

**Comment by schmupu** [comment]
Schaue einmal in die Ordner Info und History. Die sollten gefüllt sein. Ist das so?
Die anderen Werte werden gefüllt wenn Du auf Livestreamrequest oder Snapshotrequest drückst.

**Comment by mcdhrts** [comment]
Ich habe 1.1.3 getestet und hat leider bei mir keine Änderung gebracht. Bin wieder zurück auf 1.1.1 (funktioniert da wunderbar).

Meine System:
NPM
6.13.4
Node.js
v10.19.0

**Comment by schmupu** [comment]
@mcdhrts , bitte nochmals version 1.1.3 laden. Bitte vorher unter Adapter und nicht bei Instanzen den ring adapter komplett löschen

**Comment by mcdhrts** [comment]
ich werde nachher nochmal komplett neu installieren mit nodejs10 und einmal mit nodejs12 und werde dir Rückmeldung geben

**Comment by schmupu** [comment]
perfekt, würde mich interessieren ob es der Adapter dann unter nodejs 10 und  nodejs 12 funktioniert. Bei mir ist alles auf nodejs 10 eingestellt.

**Comment by schmupu** [comment]
@mcdhrts , und bitte nochmals version 1.1.3 laden. Bitte vorher unter Adapter und nicht bei Instanzen den ring adapter komplett löschen

**Comment by mcdhrts** [comment]
@schmupu ich habe meine Tests jetzt durch und habe leider keine guten Nachrichten.
Habe zwei mal eine komplett frische ioBroker Installation genommen, einmal mit der aktuellsten nodejs10 und einmal mit der aktuellsten nodejs12. Den ring Adapter über Github installiert, V1.1.3. In beiden Fällen ist das Verhalten gleich geblieben. Es werden keine Objekte angelegt. Es fehlt im Log auch der Punkt `Starting Ring Device for Id xxxx`. 
In beiden Fällen ist der Adapter noch unter Version 1.1.1. korrekt hochgekommen, Objekte wurden angelegt und befüllt, das habe ich dann danach noch einmal extra getestet.
Also irgendwas muss zwischen 1.1.1 und 1.1.2 sich verändert haben das zu dem Problem führt

**Comment by schmupu** [comment]
Nutzt du Windows, Linux, ...?

**Comment by schmupu** [comment]
Ich kann es  einfach nicht nachvollziehen, da es bei mir ohne Probleme funktioniert.

**Comment by schmupu** [comment]
Welchen js-Controller nutzt du? Ich habe den neusten 3er am start

**Comment by mcdhrts** [comment]
Ja ist natürlich schwierig wenn man es nicht nachstellen kann.
Ich habe es auf zwei verschiedenen System getestet. Einmal auf einer Synology Diskstation und einmal auf einem Raspberry Pi 3 (also beides Linux)
JS-Controller habe ich mit 3.0.20 getestet und mit der Stable Version 2.2.9. Also eigentlich wirklich alles möglich getestet. Immer das gleiche, ab 1.1.2 klappt es nicht mehr

**Comment by schmupu** [comment]
Hmm, ich habe dir gleiche Konfiguration. ioBroker im docker auf der Synology. Node 12 u. js-controller 3.20

**Comment by mcdhrts** [comment]
Das einzige das wahrscheinlich noch unterschiedlich ist, ist die Klingel an sich. Habe bei mir die "Video Doorbell Elite" am laufen. Aber ist schon komisch, habe auch den Code schon verglichen von 1.1.1 -> 1.1.2 und habe auf anhieb nichts gefunden

**Comment by schmupu** [comment]
Der große Unterschied sind die Befehle Progress. NextTick() in 1.1.2 und setImidiatly() in 1.1.3.
Aber es müsste aber eigentlich trotzdem immer Starting Ring Device for Id xxxx erscheinen.

**Comment by mcdhrts** [comment]
ich werde mir am Wochenende mal eine Fork ziehen und das setImidiatly() rausnehmen und schauen ob er dann wieder hochkommt. Dann könnten wir es evtl. weiter eingrenzen.

**Comment by mcdhrts** [comment]
hey @schmupu ,
wie angekündigt hab ich mir eine fork gezogen und habe den Adapter angefangen zu debuggen um zu schauen wo das Problem ist und habe es gefunden.
Problem ist die Änderung in der Funktion `getAllRingsDeviceObjects()` in der `ringapiclient.js`.
In 1.1.1. wurde hier geprüft auf `camera.isDoorbot`, jetzt wird der Inhalt aus `camera.deviceType` abgefragt und meine Ring ist unter keiner der Optionen dabei. Dann passiert eben genau das Verhalten, da kein `alls.push` stattfindet hat er nichts in der Hand und macht nichts und läuft denn fröhlich in einer schleife vor sich hin (`poll_ringer()`)
Wie weiter oben schon erwähnt habe ich eine "Video Doorbell Elite" und ich habe im `camera.deviceType` den Wert `jbox_v1`. Ich habe dann einmal die Optione hinzugefügt und schon klappt alles.
![image](https://user-images.githubusercontent.com/37240726/81437113-edc6a180-916a-11ea-935f-3e1cbf44947c.png)

**Comment by schmupu** [comment]
Perfekt, danke für die Hilfe! Ich habe jbox mit aufgenommen und wenn nichts gefunden wird, gibt es einen  Eintrag im Logfile. Kannst Du bitte nochmals die Version 1.1.3 von Github downloadn und testen. 
Wenn der Test erfolgreich ist, werde ich die Version morgen releasen.

**Comment by mcdhrts** [comment]
Aktuelle Version konnte positiv getestet werden. Sieht gut aus.
Vielen Dank für deine Arbeit mit dem Adapter und noch ein schönes Wochenende

**Comment by Fragggy** [comment]
Hallo zusammen, ich hatte das gleiche Problem und in meinem Log finden sich nach dem Update folgende nicht unterstützte Geräte:


```
ring.0 | 2020-05-08 22:49:16.999 | info | (100517) Device hp_cam_v2 not supported!
ring.0 | 2020-05-08 22:49:16.999 | debug | (100517) Device: {"id":9662345,"description":"Garten Tür","device_id":"341513ca0d6b","time_zone":"Europe/Berlin","subscribed":true,"subscribed_motions":true,"battery_life":100,"external_connection":fa
ring.0 | 2020-05-08 22:49:16.998 | info | (100517) Device hp_cam_v1 not supported!
```

**Comment by schmupu** [comment]
Alles klar, die hp_Cam werde ich mit aufnehmen
