### ISSUE TITLE
Fehler bei Betätigung der Klingel

### ISSUE THREAD

**Issue by death-INDEX1887** [schmupu/ioBroker.ring#29]
Beim Klingeln bekomme ich einige Fehlermeldungen im Log und der Snapshot wird nicht ordnungsgemäß erstellt. 

Für eine Lösung wäre ich dankbar.

Log:
![Logmeldungen](https://user-images.githubusercontent.com/64923986/81221092-a8776800-8fe2-11ea-97bd-edcb0dc986c1.png)

**Comment by schmupu** [comment]
Ich habe eben eine Version 1.1.3 erstellt die Du aber nur über GitHub downloaden kannst. Kannst Du die Version bitte einmal testen. 

Laden der Version 1.1.3:
Anmelden auf der ioBroker Admin Oberfläche. Auf das den Reiter Adapter wechseln. Dort oben auf die GitHub Katze (laden über externe URL) klicken und in der Liste den Ring Adapter auswählen und laden. Ist das durch, den Ring Adapter neu starten.

**Comment by death-INDEX1887** [comment]
Habe es mit jetzt mir der Version 1.1.3 probiert. Folgender Log entsteht:

![Log 2.0](https://user-images.githubusercontent.com/64923986/81226634-73234800-8feb-11ea-9e93-d3976f23f592.png)

**Comment by schmupu** [comment]
Bite nochmals die Version 1.1.3 laden. Ggf. musst du ffmpeg wenn es fehlt installieren.

`sudo apt-get install ffmpeg`

Laden der Version 1.1.3:
Anmelden auf der ioBroker Admin Oberfläche. Auf das den Reiter Adapter wechseln. Dort oben auf die GitHub Katze (laden über externe URL) klicken und in der Liste den Ring Adapter auswählen und laden. Ist das durch, den Ring Adapter neu starten.

**Comment by death-INDEX1887** [comment]
Das hat schonmal etwas gebracht. Ein Livestream wird nun ordnungsgemäß erstellt. 
Der Ausschnitt vom Livestream ist aktuell, jedoch bekomme ich keinen aktuellen Snapshot beim Klingeln, sondern einen alten. 
Gibt es dafür eine Erklärung?

**Comment by schmupu** [comment]
In der README steht, dass die Snapshot und die Livestream noch BETA ist. Da werde ich wenig machen können. 
Kann ich den Issue schließen?

**Comment by schmupu** [comment]
Nachtrag: Ich habe es bei mir nochmals die Snapshot Funktionalität getestet. Funktionierte ohne Probleme

**Comment by death-INDEX1887** [comment]
Alles gut! Hätte ja sein können, dass du eine Idee gehabt hättest. 

Vielen Dank für die schnelle und kompetente Hilfe! 😊
