### ISSUE TITLE
Ring Floodlight Cam

### ISSUE THREAD

**Issue by jogibear9988** [schmupu/ioBroker.ring#3]
Is it possible to support other Ring Cameras too?

**Comment by schmupu** [comment]
If you add the floodlight cam you see any objects?

**Comment by schmupu** [comment]
Okay, looks good. I will support the camera in the next version. What feature does the camera have in the app? History, Motion? Can you see a live Stream and talk through the cam?

**Comment by jogibear9988** [comment]
Yes to all. 

And also, I can switch on an Alarm, and I can switch on the light!

**Comment by jogibear9988** [comment]
maybe I can find it out. I will install the camera next week (I only tested it on my table atm). 
then I can do some tests or wireshark logging.

**Comment by schmupu** [comment]
great, I also add a minute ago "light on/off". But I do not know if it will work. Interesting will, which datapoints are missing and which one will not be necessary for the cam.

**Comment by jogibear9988** [comment]
with your new module the camera is found:

<img width="1344" alt="bildschirmfoto 2018-12-30 um 12 07 10" src="https://user-images.githubusercontent.com/364896/50546652-8e2dbd00-0c2b-11e9-8e0d-af2ba7bc9a57.png">
<img width="1339" alt="bildschirmfoto 2018-12-30 um 12 07 20" src="https://user-images.githubusercontent.com/364896/50546654-971e8e80-0c2b-11e9-8517-5bbeee2f4c6c.png">

**Comment by schmupu** [comment]
Das sieht ja schon mal super aus! Was passiert, wenn Du auf "livestreamrequest" drückst? Und kannst Du du bitte nochmals über die Katze und externen Link die Version installieren und Instanz starten. Dann sollte noch ein Button "Light" auftauchen. Wenn Du den drückst geht hoffentlich das Licht an.

**Comment by jogibear9988** [comment]
https://github.com/jimhigson/ring-api/issues/15

**Comment by schmupu** [comment]
Ich habe da auch noch etwas gefunden: [https://github.com/dgreif/ring-api](https://github.com/dgreif/ring-api) . Passt das?

**Comment by jogibear9988** [comment]
Das Licht schalten funktioniert noch nicht richtig gut, schalten geht nur ab und zu. Und wenn ich den Zustand übers Handy ändere ändert sich der Wert der Variable nicht (In der Handy App hingegen schon wenn ich über IOBroker anschalte)

**Comment by schmupu** [comment]
Schalten über ioBroker hätte ich mir gewünscht, dass es funktioniert.  Muss mal sehen ob ich da noch etwas optimieren kann.

**Comment by jogibear9988** [comment]
Ich werde es die Woche genauer analysieren wenn die Kamera angebracht ist.

Gibt es den sowas wie ein SIP Widget für VIS mit welchem man dann die Kamera nutzen kann?

**Comment by schmupu** [comment]
Moin, Zeit zum Testen gefunden? VG

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
