### ISSUE TITLE
Beim Druck auf die beiden Buttons in den Objekten passiert nichts!

### ISSUE THREAD

**Issue by leonracer** [schmupu/ioBroker.ring#30]
hallo,

Wenn ich die Knöpfe drücke passiert nichts. Es wird weder ein Snapshot noch ein Video angelegt. Was mache ich hier falsch!

Danke.

Leonracer

**Comment by schmupu** [comment]
Moin, 
ein wenig Hintergrundinformationen wären hilfreich wie z.B. welche Ring Version nutzt du? Welche Node Version und System, was steht im Logfile, ....
VG

**Comment by schmupu** [comment]
Falls Du die Version 1.1.2 oder 1.1.3 nutzt dann bitte (nochmals) die Version 1.1.3 laden

Laden der Version 1.1.3:
Anmelden auf der ioBroker Admin Oberfläche. Auf das den Reiter Adapter wechseln. Dort oben auf die GitHub Katze (laden über externe URL) klicken und in der Liste den Ring Adapter auswählen und laden. Ist das durch, den Ring Adapter neu starten.

**Comment by leonracer** [comment]
Oh Mann, du bist ja flink.

Ich benutze den 1.1.1 Adapter und habe bei dem 1.1.0 am Samstag begonnen. Hier mal meine Sysinfos:

![C200225E-8AB5-4753-854C-3B3CE18C1335](https://user-images.githubusercontent.com/57258642/81337108-c9a38b80-90aa-11ea-8654-73437b11e2e3.png)

Wenn ich auf die Buttons drücke passiert nix.
Snapshot hat er einmal gemacht, dann nichts mehr. Livestream bleibt leer.

![3E3D71E6-6399-42B8-8DBC-4BCF74C7631C](https://user-images.githubusercontent.com/57258642/81337285-125b4480-90ab-11ea-862b-fb58cb6a2fc4.png)

Log zeigt nichts an!

**Comment by leonracer** [comment]
Die 1.1.3 macht auch nichts. Gerade probiert. Klingel ist ne Doorbell 2

**Comment by leonracer** [comment]
Habe gerade in dem anderen issue den Tipp mit ffmpeg gelesen, installiere mal nach.

**Comment by leonracer** [comment]
Auch mit ffmpeg keine besserung

**Comment by schmupu** [comment]
Drücke bitte nochmals auf die Knöpfe und schaue dann ins Logfile. Steht da etwas von Starting snapshot oder Starting Livestern?

**Comment by leonracer** [comment]
Nein steht gar nix in der Richtung da, schade! Hab jetzt auch den Adapter deinstalliert und neu installiert. Dann den Token generiert und die Objekte wurden auch angelegt. Knöpfe sind weiterhin ohne Funktion.

**Comment by schmupu** [comment]
Hast du sich für Version 1.1.3 installiert? Wenn das nicht geht, Versuche es mit der Version 1.1.1.
Wie sieht es jetzt aus?

**Comment by leonracer** [comment]
Hi,

hier wäre die Fehlermeldung nun!

![grafik](https://user-images.githubusercontent.com/57258642/81421726-3756c280-9152-11ea-8681-821afd6679f4.png)

**Comment by schmupu** [comment]
Die Warnung habe ich aber auch. Landen denn die snapshots und Livestreams in dem Verzeichnis

**Comment by leonracer** [comment]
Nö, eben nicht. Die Ordner bleiben einfach leer.

**Comment by schmupu** [comment]
Bitte und Logfile schauen, ob sich etwas geändert hat und mir schicken.

**Comment by leonracer** [comment]
Geht jetzt urplötzlich. Daher mache ich jetzt hier zu. Vielen Dank für den Support
