### ISSUE TITLE
writeFile will not write this file...

### ISSUE THREAD

**Issue by mark77-DE** [schmupu/ioBroker.ring#31]
Moin,

Im IoBroker Log kommen bei mir folgende Meldungen:

`
ring.0	2020-05-12 11:51:14.923	warn	(12466) writeFile will not write this file (doorbell_########/snapshot_1589277047032.jpg) in future versions: ring.0 is not an object of type "meta"
ring.0	2020-05-12 11:51:14.919	info	(12466) Done creating snapshot
ring.0	2020-05-12 11:51:07.506	warn	(12466) writeFile will not write this file (doorbell_########/livestream_1589277047032.mp4) in future versions: ring.0 is not an object of type "meta"
ring.0	2020-05-12 11:51:07.505	info	(12466) Done creating livestream
ring.0	2020-05-12 11:50:47.070	info	(12466) Starting creating snapshot
ring.0	2020-05-12 11:50:47.066	info	(12466) Starting creating livestream with recording time 10 sec.
ring.0	2020-05-12 11:50:47.028	info	(12466) Ding Dong for Id ######## (motion, ringing)
ring.0	2020-05-12 11:36:07.234	warn	(12466) writeFile will not write this file (doorbell_########/snapshot_1589276138861.jpg) in future versions: ring.0 is not an object of type "meta"
ring.0	2020-05-12 11:36:07.233	info	(12466) Done creating snapshot
ring.0	2020-05-12 11:35:59.270	warn	(12466) writeFile will not write this file (doorbell_########/livestream_1589276138862.mp4) in future versions: ring.0 is not an object of type "meta"
ring.0	2020-05-12 11:35:59.269	info	(12466) Done creating livestream
ring.0	2020-05-12 11:35:38.910	info	(12466) Starting creating snapshot
ring.0	2020-05-12 11:35:38.903	info	(12466) Starting creating livestream with recording time 10 sec.
ring.0	2020-05-12 11:35:38.858	info	(12466) Ding Dong for Id ######## (motion, ringing)
ring.0	2020-05-12 11:22:14.026	warn	(12466) writeFile will not write this file (doorbell_########/livestream_1589275313619.mp4) in future versions: ring.0 is not an object of type "meta"
ring.0	2020-05-12 11:22:14.025	info	(12466) Done creating livestream
ring.0	2020-05-12 11:21:53.732	warn	(12466) writeFile will not write this file (doorbell_########/snapshot_1589275313693.jpg) in future versions: ring.0 is not an object of type "meta"
ring.0	2020-05-12 11:21:53.732	info	(12466) Done creating snapshot
ring.0	2020-05-12 11:21:53.731	info	(12466) Starting creating snapshot
ring.0	2020-05-12 11:21:53.659	info	(12466) Starting creating livestream with recording time 10 sec.
ring.0	2020-05-12 11:21:53.655	warn	(12466) writeFile will not write this file (doorbell_########/snapshot_1589275313619.jpg) in future versions: ring.0 is not an object of type "meta"
ring.0	2020-05-12 11:21:53.653	info	(12466) Done creating snapshot
ring.0	2020-05-12 11:21:53.652	info	(12466) Starting creating snapshot
ring.0	2020-05-12 11:21:53.614	info	(12466) Ding Dong for Id ######## (ding, ringing)
ring.0	2020-05-12 11:21:01.037	warn	(12466) writeFile will not write this file (doorbell_########/snapshot_1589275232443.jpg) in future versions: ring.0 is not an object of type "meta"
ring.0	2020-05-12 11:21:01.034	info	(12466) Done creating snapshot
ring.0	2020-05-12 11:20:52.870	warn	(12466) writeFile will not write this file (doorbell_########/livestream_1589275232445.mp4) in future versions: ring.0 is not an object of type "meta"
ring.0	2020-05-12 11:20:52.865	info	(12466) Done creating livestream
ring.0	2020-05-12 11:20:32.507	info	(12466) Starting creating snapshot
ring.0	2020-05-12 11:20:32.502	info	(12466) Starting creating livestream with recording time 10 sec.
ring.0	2020-05-12 11:20:32.438	info	(12466) Ding Dong for Id ######## (motion, ringing)
`

Sind die Warnungen:
`writeFile will not write this file (doorbell_########/livestream_1589275232445.mp4) in future versions: ring.0 is not an object of type "meta"`
und
`writeFile will not write this file (doorbell_########/snapshot_1589275232443.jpg) in future versions: ring.0 is not an object of type "meta"`
bereits bekannt oder ein Fehler bei mir?

Gruß,
Mark

**Comment by schmupu** [comment]
Warning ist kein Fehler😊 ist bekannt

**Comment by Bjoern2006** [comment]
**ERRORMeldung:**
ring.0 | 2021-03-25 17:12:39.034 | error | (21125) Error: Error setSanpshot()): Error: ring.0 is not an object of type "meta"
-- | -- | -- | --
ring.0 | 2021-03-25 17:12:39.032 | error | (21125) Cannot write file doorbell_XXXXXXX/snapshotXXXXXXX_1616688742642.jpg: ring.0 is not an object of type "meta"

Gibt's dazu eine Lösung?
