### ISSUE TITLE
Livestream Doorbell 2

### ISSUE THREAD

**Issue by Hini2001** [schmupu/ioBroker.ring#32]
Moin, 

Ich mal wieder. Nachdem offensichtlich mein Token abgelaufen war, da ich einen neuen erstellen musste, nimmt meine Doorbell neuerdings egal welche Einstellungen ich vornehme bei einem Livestream Request 10 Minuten auf. Das verringert natürlich massiv DEN Akku. 
Ist dieses Problem nur bei mir? 
Habe noch keine Neuinstallation des Adapters vorgenommen. 

Wüsste auch nicht, wo ich irgendwelche Änderungen vornehmen sollte. Weder in der App noch im Adapter.

Die Stickup Cam macht weiterhin alles was sie soll. 10 Sekunden so wie eingestellt. 

Außerdem ist mir aufgefallen, dass mit zu nehmende Nutzungsdauer bzw. seit dem Update auf 1.1.3 Snapshots nur noch ganz selten mal funktionieren. 

Viele Grüße 
Hinrich

**Comment by schmupu** [comment]
Du kannst in der Konfiguration der Ring Instanz die Dauer des Videos in Sekunden einstellen.

**Comment by Hini2001** [comment]
Ja das weiß ich. Da habe ich ja auch 10 Sekunden eingestellt. Bis zum token refresh hat das auch funktioniert.
Ich trigger per blockly 1 mal die Stunde für ein 10 Sekunden Video. Die doorbell und die StickUpCam. 
Er speichert auch 10 Sekunden Videos ab. Aber die doorbell nimmt 10 Minuten auf. Dies kann ich dann in der App sehen. 🙈
Von daher hab ich das Skript erstmal abgestellt. Bei der StickUpCam klappt das optimal.

Hast du ne Idee wegen der snapshots? Warum die nicht mehr so häufig klappen wie vor ein paar Wochen?

**Comment by BenediktEnger** [comment]
Ich möchte mich mal hier anschließen zum Thema Snapshots.
Der erzeugte Link zum Snapshot wird nur sehr selten aktualisiert. Ich konnte hier noch kein Schema ausmachen (nach Adapter start o.ä.).
Die Datei wird zwar immer neu erstellt, enthält aber ein altes Bild.

Mache ich was falsch? der Livestream ist immer aktuell.

**Comment by schmupu** [comment]
Da werde ich leider nichts machen können. Ich habe lange überlegt ob ich überhaupt die Livestream und Snapshot Funktion anbiete da diese so unregelmässig funktioniert. Das ist bei mir auch so. Mal geht es und dann wieder für Tage nicht.

**Comment by p3pp0** [comment]
@schmupu gibt es hier vielleicht etwas neues? :-)

**Comment by nhet** [comment]
Hallöchen, 
ich habe das gleiche Problem wie @Hini2001 gemeldet hat. Sobald ich den Adapter starte, werden sämtliche motion und ding events "angenommen" und eine Aufzeichnung von 10Minuten gemacht.
Was kann man dagegen machen? Gibt es irgendwo eine Einstellung die ich übersehen habe?
