### ISSUE TITLE
Snapshot/Livestream File und URL verschieden

### ISSUE THREAD

**Issue by Hini2001** [schmupu/ioBroker.ring#33]
Moin moin,

ich mal wieder. Nach meinem Umzug mit dem IOBroker vom Beelink BT3 Pro (Windows 10) auf den Raspi 4 habe ich folgendes "Problem" festgestellt:

Der Datenpunkt FILE und URL verweisen auf verschiedene Orte?
Und der Ort der URL Existiert so nicht mehr (von daher wohl auch die WARN im Log!?):

`
writeFile | 2020-06-11 10:02:36.260 | warn | will not write this file (doorbell_27593363/livestream27593363_1591861919788.mp4) in future versions: ring.0 is not an object of type "meta"
-- | -- | -- | --
ring.0 | 2020-06-11 10:02:36.255 | warn | (2555) writeFile will not write this file (doorbell_27593363/livestream27593363_1591861919788.mp4) in future versions: ring.0 is not an object of type "meta"
`

Der Datenpunkt des FILE z.B. zeigt auf die richtige Datei:
`
/opt/iobroker/node_modules/iobroker.ring/snapshot/livestream45343751_1591861871780.mp4
`

Der Datenpunkt der URL zeigt auf eine nicht existende Quelle (jedoch unter Windows war sie vorhanden):
`
http://raspberrypi-IOB:8082/ring.0/cocoa_45343751/livestream45343751_1591861871780.mp4
`

Eine Neuinstallation des Adapters hat keine Abhilfe geschaffen.
Ist dies vielleicht sogar ein "Problem" in einer anderen Config? Des IOBrokers selber?

Ich habe den Umzug mit einem durch BackitUp erstellten Backups gemacht.

Ich weiß. ich störe öfter mal mit Problemen.

Das Problem, dass bei einem Livestream der Ring Doorbell 2 auch immer noch ein 10 Minuten Video erstellt ist leider auch noch vorhanden. Aber da glaube ich mittlerweile fast, dass es an RING selber liegt. Da die Doorbell ab und an sogar 10 Minuten Videos erstellt, bei Bewegungs Erkennung?!

Sorry fürs erneute "Problem".

Viele Grüße
Hinrich

**Comment by schmupu** [comment]
Die snapshot und mp4 Funktionalität ist Beta und bleibt beta. Steht auch in der Readme.
Sorry!
