### ISSUE TITLE
RING Floodlight 

### ISSUE THREAD

**Issue by biggesee** [schmupu/ioBroker.ring#34]
Hallo Schmupu,

die "Floodlight" wird nicht korrekt abbgebildet - ich kann z.B. die Bewegungsmelder nicht in den Objekten finden. Bin mir aber auch nicht sicher ob das wirklich als Fehler zu sehen ist, kann also ggf. als Feature reqeust gehandhabt werden ;-)

--------------------------------------------------
the floodlight is not displayed correctly - I cannot see the sensors for motion detection.
But I'm also not sure whether this should really be seen as an error, can also be handled as a feature if necessary ;-)
--------------------------------------------------

Frank

**Comment by biggesee** [comment]
so also https://forum.iobroker.net/topic/34542/bewegungsmelder-einer-ring-floodlight-anzapfen

**Comment by schmupu** [comment]
Die Ring API bietet leider das Feature nicht an. Damit kann ich es auch nicht in ioBroker darstellen. Sorry.
