### ISSUE TITLE
Kein Snap bei 1.1.3

### ISSUE THREAD

**Issue by Wurzeldoktor** [schmupu/ioBroker.ring#35]
Hallo, absoluter Neuling hier, daher bereits jetzt big Sorry

Ich möchte den Snap der Doorbell 2 abgreifen, wenn ich es richtig verstanden habe so macht der Adapter beim klingeln einen automatischen Snap?!

Leider funktioniert das bei mir scheinbar nicht :(
bekomme im Log folgende Zeile:

ring.0 | 2020-07-07 12:16:54.227 | error | (15904) Error: Error setSanpshot()): Error: Could not create Snapshot for 47963712 in getSnapshot(). Error: Snapshot failed to refresh after 40 attempts -- | -- | -- | --

habe bereits versucht den Snap in nem bereits vorhandenem (rechte komplett offen!) Ordner für die ESP Cam zu speicher. 
auch hier passiert nicht. 
![log](https://user-images.githubusercontent.com/67959374/86780746-5e037d80-c05d-11ea-9e27-9b14b8e3c26f.png)
![config](https://user-images.githubusercontent.com/67959374/86780762-622f9b00-c05d-11ea-9e27-387cb9298437.png)

Danke schonmal :)

**Comment by Wurzeldoktor** [comment]
Log wenn ich auf einen der beiden Buttons (snap oder Livestream) drücke


ring.0 | 2020-07-07 14:27:07.490 | info | (17972) Starting Ring Device for Id 47963712
-- | -- | -- | --
ring.0 | 2020-07-07 14:27:04.682 | info | (17972) Starting Adapter ring.0 in version 1.1.3
ring.0 | 2020-07-07 14:27:04.638 | info | (17972) starting. Version 1.1.3 in /opt/iobroker/node_modules/iobroker.ring, node: v12.18.1
host.tinkerboard | 2020-07-07 14:27:02.402 | info | instance system.adapter.ring.0 started with pid 17972
host.tinkerboard | 2020-07-07 12:26:32.372 | info | Restart adapter system.adapter.ring.0 because enabled
host.tinkerboard | 2020-07-07 12:26:32.372 | info | instance system.adapter.ring.0 terminated with code 0 (NO_ERROR)
host.tinkerboard | 2020-07-07 12:26:32.371 | error | Caught by controller[2]: (node:17782) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js proc
host.tinkerboard | 2020-07-07 12:26:32.370 | error | Caught by controller[2]: (node:17782) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by
host.tinkerboard | 2020-07-07 12:26:32.370 | error | Caught by controller[1]: at processTicksAndRejections (internal/process/task_queues.js:97:5)
host.tinkerboard | 2020-07-07 12:26:32.369 | error | Caught by controller[1]: at fulfilled (/opt/iobroker/node_modules/iobroker.ring/node_modules/ring-client-api/lib/api/sip-session.js:5:58)
host.tinkerboard | 2020-07-07 12:26:32.369 | error | Caught by controller[1]: at Generator.next (<anonymous>)
host.tinkerboard | 2020-07-07 12:26:32.369 | error | Caught by controller[1]: at SipSession.<anonymous> (/opt/iobroker/node_modules/iobroker.ring/node_modules/ring-client-api/lib/api/sip-session.js:125:16)
host.tinkerboard | 2020-07-07 12:26:32.368 | error | Caught by controller[1]: at FfmpegProcess.start (/opt/iobroker/node_modules/iobroker.ring/node_modules/ring-client-api/lib/api/ffmpeg.js:76:23)
host.tinkerboard | 2020-07-07 12:26:32.368 | error | Caught by controller[1]: at Socket.Writable.write (_stream_writable.js:318:11)
host.tinkerboard | 2020-07-07 12:26:32.367 | error | Caught by controller[1]: at writeOrBuffer (_stream_writable.js:387:5)
host.tinkerboard | 2020-07-07 12:26:32.359 | error | Caught by controller[1]: at doWrite (_stream_writable.js:399:19)
host.tinkerboard | 2020-07-07 12:26:32.359 | error | Caught by controller[1]: (node:17782) UnhandledPromiseRejectionWarning: Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
host.tinkerboard | 2020-07-07 12:26:32.359 | error | Caught by controller[0]: }
host.tinkerboard | 2020-07-07 12:26:32.359 | error | Caught by controller[0]: ]
host.tinkerboard | 2020-07-07 12:26:32.359 | error | Caught by controller[0]: '/opt/iobroker/node_modules/iobroker.ring/snapshot/Stream'
host.tinkerboard | 2020-07-07 12:26:32.358 | error | Caught by controller[0]: '2',
host.tinkerboard | 2020-07-07 12:26:32.358 | error | Caught by controller[0]: '-t',
host.tinkerboard | 2020-07-07 12:26:32.358 | error | Caught by controller[0]: 'copy',
host.tinkerboard | 2020-07-07 12:26:32.358 | error | Caught by controller[0]: '-vcodec',
host.tinkerboard | 2020-07-07 12:26:32.357 | error | Caught by controller[0]: 'aac',
host.tinkerboard | 2020-07-07 12:26:32.357 | error | Caught by controller[0]: '-acodec',
host.tinkerboard | 2020-07-07 12:26:32.357 | error | Caught by controller[0]: 'pipe:',
host.tinkerboard | 2020-07-07 12:26:32.357 | error | Caught by controller[0]: '-i',
host.tinkerboard | 2020-07-07 12:26:32.356 | error | Caught by controller[0]: '-re',
host.tinkerboard | 2020-07-07 12:26:32.356 | error | Caught by controller[0]: 'sdp',
host.tinkerboard | 2020-07-07 12:26:32.356 | error | Caught by controller[0]: '-f',
host.tinkerboard | 2020-07-07 12:26:32.356 | error | Caught by controller[0]: 'pipe,udp,rtp,file,crypto',
host.tinkerboard | 2020-07-07 12:26:32.355 | error | Caught by controller[0]: '-protocol_whitelist',
host.tinkerboard | 2020-07-07 12:26:32.355 | error | Caught by controller[0]: '-hide_banner',
host.tinkerboard | 2020-07-07 12:26:32.354 | error | Caught by controller[0]: spawnargs: [
host.tinkerboard | 2020-07-07 12:26:32.354 | error | Caught by controller[0]: path: 'ffmpeg',
host.tinkerboard | 2020-07-07 12:26:32.354 | error | Caught by controller[0]: syscall: 'spawn ffmpeg',
host.tinkerboard | 2020-07-07 12:26:32.353 | error | Caught by controller[0]: code: 'ENOENT',
host.tinkerboard | 2020-07-07 12:26:32.353 | error | Caught by controller[0]: errno: 'ENOENT',
host.tinkerboard | 2020-07-07 12:26:32.353 | error | Caught by controller[0]: at processTicksAndRejections (internal/process/task_queues.js:84:21) {
host.tinkerboard | 2020-07-07 12:26:32.352 | error | Caught by controller[0]: at onErrorNT (internal/child_process.js:469:16)
host.tinkerboard | 2020-07-07 12:26:32.352 | error | Caught by controller[0]: at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
host.tinkerboard | 2020-07-07 12:26:32.345 | error | Caught by controller[0]: Error: spawn ffmpeg ENOENT
ring.0 | 2020-07-07 12:26:31.469 | info | (17782) Terminated (NO_ERROR): Without reason
ring.0 | 2020-07-07 12:26:31.467 | info | (17782) terminating
ring.0 | 2020-07-07 12:26:31.450 | info | (17782) Closing Adapter
ring.0 | 2020-07-07 12:26:31.449 | error | at processTicksAndRejections (internal/process/task_queues.js:84:21)
ring.0 | 2020-07-07 12:26:31.449 | error | at onErrorNT (internal/child_process.js:469:16)
ring.0 | 2020-07-07 12:26:31.449 | error | at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
ring.0 | 2020-07-07 12:26:31.449 | error | (17782) Error: spawn ffmpeg ENOENT
ring.0 | 2020-07-07 12:26:31.448 | error | (17782) uncaught exception: spawn ffmpeg ENOENT
ring.0 | 2020-07-07 12:26:31.157 | info | (17782) Starting creating livestream with recording time 2 sec.
ring.0 | 2020-07-07 12:26:29.549 | info | (17782) Starting creating snapshot

**Comment by schmupu** [comment]
Wie es in der README steht, snapshot und livestream ist Beta. Ich habe das keinen Einfluss drauf wie gut es funktioniert und kann da auch nicht korrigieren. Sorry.
