### ISSUE TITLE
Steam in VIS einfügen

### ISSUE THREAD

**Issue by oneill2612** [schmupu/ioBroker.ring#41]
Hey Sry ich weiß nicht genau ob ich hier richtig bin,
Ich habe mein VIS gerade fast fertig und jetzt wollte ich meine RING CAMs hinzufügen. Ich habe meinen Key über die Console bekommen und das hat alles geklappt.

Kann mir jemand sagen wie ich die Cams einfüge

**Comment by oneill2612** [comment]
Konsolen Code

cd /opt/iobroker/node_modules/iobroker.ring/
dann:
npm i ring-client-api

dann:

cd /opt/iobroker/node_modules/iobroker.ring/node_modules/ring-client-api
node ring-auth-cli
1

**Comment by schmupu** [comment]
ich habe das problem noch nicht ganz verstanden. wird  die ring in iobroker  eingebunden?

**Comment by oneill2612** [comment]
Ne eingebunden sind sie ich will sie in VIS einbinden damit ich die immer sehe habe mir eine VIS oberfläche gebastelt. Aber jetzt muss ich die Ring Cams ja iwie da einbinden

**Comment by schmupu** [comment]
da kann ich leider nicht helfen. frage einmal im forum nach
