### ISSUE TITLE
Could not get Health

### ISSUE THREAD

**Issue by lordnaicon** [schmupu/ioBroker.ring#9]
Hi 
Habe seid einiger zeit immer diesen Fehler: 

`Could not get Health for 17129860 in getHealthSummarie(id). Could not get Health for [object Object] in getHealth(id). Error: API returned Status Code 404`

MfG Lordi

**Comment by schmupu** [comment]
Problem ist bekannt, es gibt aber keine Lösung. Es tritt nur bei einigen Usern auf und teilweise auch nur für ein paar Tage und dann geht es wieder. Hatte ich auch schon gehabt.
Welche Version vom Ring Adapter hast du laufen? Kannst du den Usernmane und Passwort in der Ring Konfiguraiton im ioBroker Adapter nochmals eingeben.
Wenn das nicht geht, kann man zwischen 2 APIs wechseln in der Konfiguration. Versuche das einmal

**Comment by lordnaicon** [comment]
Hi habe die 1.0.4 Version
`

ring.0 | 2019-06-05 13:19:29.315 | info | Could  not get Health for 17129860 in getHealthSummarie(id). Could not get  Health for [object Object] in getHealth(id). Error: API returned Status  Code 404
-- | -- | -- | --
ring.0 | 2019-06-05 13:19:28.422 | info | Starting Ring Device for Id 17129860
ring.0 | 2019-06-05 13:19:25.688 | info | Starting Ring Device for Id 17118188
ring.0 | 2019-06-05 13:19:22.653 | info | Ring adapter uses API: doorbot
ring.0 | 2019-06-05 13:19:22.653 | info | Starting Adapter ring.0 in version 1.0.4
ring.0 | 2019-06-05 13:19:22.477 | info | starting. Version 1.0.4 in /opt/iobroker/node_modules/iobroker.ring, node: v8.16.0`

Habe mal wie du vorgeschlagen hast API gewechselt und bekomme jetzt keine Fehler mehr. 

`

ring.0 | 2019-06-05 13:21:18.734 | info | Starting Ring Device for Id 17129860
-- | -- | -- | --
ring.0 | 2019-06-05 13:21:15.909 | info | Starting Ring Device for Id 17118188
ring.0 | 2019-06-05 13:21:12.780 | info | Ring adapter uses API: ring-api
ring.0 | 2019-06-05 13:21:12.780 | info | Starting Adapter ring.0 in version 1.0.4
ring.0 | 2019-06-05 13:21:12.216 | info | starting. Version 1.0.4 in /opt/iobroker/node_modules/iobroker.ring, node: v8.16.0`

Danke 

MfG Lordi
